// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth_tokens.sql

package postgres

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAuthToken = `-- name: CreateAuthToken :one
INSERT INTO auth_tokens (
    user_id,
    jwt_token,
    refresh_token,
    expires_at
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, jwt_token, refresh_token, expires_at, created_at
`

type CreateAuthTokenParams struct {
	UserID       uuid.UUID      `json:"user_id"`
	JwtToken     string         `json:"jwt_token"`
	RefreshToken sql.NullString `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
}

func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error) {
	row := q.queryRow(ctx, q.createAuthTokenStmt, createAuthToken,
		arg.UserID,
		arg.JwtToken,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JwtToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAuthToken = `-- name: DeleteAuthToken :exec
DELETE FROM auth_tokens
WHERE id = $1
`

func (q *Queries) DeleteAuthToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteAuthTokenStmt, deleteAuthToken, id)
	return err
}

const deleteAuthTokenByJWT = `-- name: DeleteAuthTokenByJWT :exec
DELETE FROM auth_tokens
WHERE jwt_token = $1
`

func (q *Queries) DeleteAuthTokenByJWT(ctx context.Context, jwtToken string) error {
	_, err := q.exec(ctx, q.deleteAuthTokenByJWTStmt, deleteAuthTokenByJWT, jwtToken)
	return err
}

const deleteExpiredAuthTokens = `-- name: DeleteExpiredAuthTokens :exec
DELETE FROM auth_tokens
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredAuthTokens(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteExpiredAuthTokensStmt, deleteExpiredAuthTokens)
	return err
}

const getAuthTokenByJWT = `-- name: GetAuthTokenByJWT :one
SELECT id, user_id, jwt_token, refresh_token, expires_at, created_at FROM auth_tokens
WHERE jwt_token = $1
`

func (q *Queries) GetAuthTokenByJWT(ctx context.Context, jwtToken string) (AuthToken, error) {
	row := q.queryRow(ctx, q.getAuthTokenByJWTStmt, getAuthTokenByJWT, jwtToken)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JwtToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthTokensByUserID = `-- name: GetAuthTokensByUserID :many
SELECT id, user_id, jwt_token, refresh_token, expires_at, created_at FROM auth_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAuthTokensByUserID(ctx context.Context, userID uuid.UUID) ([]AuthToken, error) {
	rows, err := q.query(ctx, q.getAuthTokensByUserIDStmt, getAuthTokensByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthToken
	for rows.Next() {
		var i AuthToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JwtToken,
			&i.RefreshToken,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthTokenRefreshToken = `-- name: UpdateAuthTokenRefreshToken :exec
UPDATE auth_tokens
SET refresh_token = $2
WHERE id = $1
`

type UpdateAuthTokenRefreshTokenParams struct {
	ID           uuid.UUID      `json:"id"`
	RefreshToken sql.NullString `json:"refresh_token"`
}

func (q *Queries) UpdateAuthTokenRefreshToken(ctx context.Context, arg UpdateAuthTokenRefreshTokenParams) error {
	_, err := q.exec(ctx, q.updateAuthTokenRefreshTokenStmt, updateAuthTokenRefreshToken, arg.ID, arg.RefreshToken)
	return err
}
