// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth_state.sql

package postgres

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAuthState = `-- name: CreateAuthState :one
INSERT INTO auth_state (
    state,
    auth_url,
    expires_at
) VALUES (
    $1, $2, $3
) RETURNING state, user_id, authenticated, auth_url, expires_at, created_at
`

type CreateAuthStateParams struct {
	State     string         `json:"state"`
	AuthUrl   sql.NullString `json:"auth_url"`
	ExpiresAt time.Time      `json:"expires_at"`
}

func (q *Queries) CreateAuthState(ctx context.Context, arg CreateAuthStateParams) (AuthState, error) {
	row := q.queryRow(ctx, q.createAuthStateStmt, createAuthState, arg.State, arg.AuthUrl, arg.ExpiresAt)
	var i AuthState
	err := row.Scan(
		&i.State,
		&i.UserID,
		&i.Authenticated,
		&i.AuthUrl,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAuthState = `-- name: DeleteAuthState :exec
DELETE FROM auth_state
WHERE state = $1
`

func (q *Queries) DeleteAuthState(ctx context.Context, state string) error {
	_, err := q.exec(ctx, q.deleteAuthStateStmt, deleteAuthState, state)
	return err
}

const deleteExpiredAuthStates = `-- name: DeleteExpiredAuthStates :exec
DELETE FROM auth_state
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredAuthStates(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteExpiredAuthStatesStmt, deleteExpiredAuthStates)
	return err
}

const getAuthState = `-- name: GetAuthState :one
SELECT state, user_id, authenticated, auth_url, expires_at, created_at FROM auth_state
WHERE state = $1
`

func (q *Queries) GetAuthState(ctx context.Context, state string) (AuthState, error) {
	row := q.queryRow(ctx, q.getAuthStateStmt, getAuthState, state)
	var i AuthState
	err := row.Scan(
		&i.State,
		&i.UserID,
		&i.Authenticated,
		&i.AuthUrl,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateAuthState = `-- name: UpdateAuthState :one
UPDATE auth_state
SET
    user_id = $2,
    authenticated = $3
WHERE state = $1
RETURNING state, user_id, authenticated, auth_url, expires_at, created_at
`

type UpdateAuthStateParams struct {
	State         string        `json:"state"`
	UserID        uuid.NullUUID `json:"user_id"`
	Authenticated bool          `json:"authenticated"`
}

func (q *Queries) UpdateAuthState(ctx context.Context, arg UpdateAuthStateParams) (AuthState, error) {
	row := q.queryRow(ctx, q.updateAuthStateStmt, updateAuthState, arg.State, arg.UserID, arg.Authenticated)
	var i AuthState
	err := row.Scan(
		&i.State,
		&i.UserID,
		&i.Authenticated,
		&i.AuthUrl,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
