// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth_tokens.sql

package postgres

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deleteAuthTokenByUserID = `-- name: DeleteAuthTokenByUserID :exec
DELETE FROM google_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteAuthTokenByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteAuthTokenByUserIDStmt, deleteAuthTokenByUserID, userID)
	return err
}

const deleteExpiredAuthTokens = `-- name: DeleteExpiredAuthTokens :exec
DELETE FROM google_tokens
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredAuthTokens(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteExpiredAuthTokensStmt, deleteExpiredAuthTokens)
	return err
}

const getAuthTokenByUserID = `-- name: GetAuthTokenByUserID :one
SELECT user_id, access_token, refresh_token, expires_at, created_at FROM google_tokens
WHERE user_id = $1
`

func (q *Queries) GetAuthTokenByUserID(ctx context.Context, userID uuid.UUID) (GoogleToken, error) {
	row := q.queryRow(ctx, q.getAuthTokenByUserIDStmt, getAuthTokenByUserID, userID)
	var i GoogleToken
	err := row.Scan(
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateAuthTokenRefreshToken = `-- name: UpdateAuthTokenRefreshToken :exec
UPDATE google_tokens
SET refresh_token = $2
WHERE user_id = $1
`

type UpdateAuthTokenRefreshTokenParams struct {
	UserID       uuid.UUID      `json:"user_id"`
	RefreshToken sql.NullString `json:"refresh_token"`
}

func (q *Queries) UpdateAuthTokenRefreshToken(ctx context.Context, arg UpdateAuthTokenRefreshTokenParams) error {
	_, err := q.exec(ctx, q.updateAuthTokenRefreshTokenStmt, updateAuthTokenRefreshToken, arg.UserID, arg.RefreshToken)
	return err
}

const upsertAuthToken = `-- name: UpsertAuthToken :one
INSERT INTO google_tokens (
    user_id,
    access_token,
    refresh_token,
    expires_at
) VALUES (
    $1, $2, $3, $4
) ON CONFLICT (user_id) DO UPDATE SET
    access_token = COALESCE(NULLIF($2, ''), google_tokens.access_token),
    refresh_token = COALESCE(NULLIF($3, ''), google_tokens.refresh_token),
    expires_at = $4
RETURNING user_id, access_token, refresh_token, expires_at, created_at
`

type UpsertAuthTokenParams struct {
	UserID       uuid.UUID      `json:"user_id"`
	AccessToken  sql.NullString `json:"access_token"`
	RefreshToken sql.NullString `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
}

func (q *Queries) UpsertAuthToken(ctx context.Context, arg UpsertAuthTokenParams) (GoogleToken, error) {
	row := q.queryRow(ctx, q.upsertAuthTokenStmt, upsertAuthToken,
		arg.UserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	var i GoogleToken
	err := row.Scan(
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
