// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createAuthStateStmt, err = db.PrepareContext(ctx, createAuthState); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAuthState: %w", err)
	}
	if q.createAuthTokenStmt, err = db.PrepareContext(ctx, createAuthToken); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAuthToken: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteAuthStateStmt, err = db.PrepareContext(ctx, deleteAuthState); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAuthState: %w", err)
	}
	if q.deleteAuthTokenStmt, err = db.PrepareContext(ctx, deleteAuthToken); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAuthToken: %w", err)
	}
	if q.deleteAuthTokenByJWTStmt, err = db.PrepareContext(ctx, deleteAuthTokenByJWT); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAuthTokenByJWT: %w", err)
	}
	if q.deleteExpiredAuthStatesStmt, err = db.PrepareContext(ctx, deleteExpiredAuthStates); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteExpiredAuthStates: %w", err)
	}
	if q.deleteExpiredAuthTokensStmt, err = db.PrepareContext(ctx, deleteExpiredAuthTokens); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteExpiredAuthTokens: %w", err)
	}
	if q.getAuthStateStmt, err = db.PrepareContext(ctx, getAuthState); err != nil {
		return nil, fmt.Errorf("error preparing query GetAuthState: %w", err)
	}
	if q.getAuthTokenByJWTStmt, err = db.PrepareContext(ctx, getAuthTokenByJWT); err != nil {
		return nil, fmt.Errorf("error preparing query GetAuthTokenByJWT: %w", err)
	}
	if q.getAuthTokensByUserIDStmt, err = db.PrepareContext(ctx, getAuthTokensByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAuthTokensByUserID: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.updateAuthStateStmt, err = db.PrepareContext(ctx, updateAuthState); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAuthState: %w", err)
	}
	if q.updateAuthTokenRefreshTokenStmt, err = db.PrepareContext(ctx, updateAuthTokenRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAuthTokenRefreshToken: %w", err)
	}
	if q.updateUserStmt, err = db.PrepareContext(ctx, updateUser); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUser: %w", err)
	}
	if q.updateUserByEmailStmt, err = db.PrepareContext(ctx, updateUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserByEmail: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createAuthStateStmt != nil {
		if cerr := q.createAuthStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAuthStateStmt: %w", cerr)
		}
	}
	if q.createAuthTokenStmt != nil {
		if cerr := q.createAuthTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAuthTokenStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteAuthStateStmt != nil {
		if cerr := q.deleteAuthStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAuthStateStmt: %w", cerr)
		}
	}
	if q.deleteAuthTokenStmt != nil {
		if cerr := q.deleteAuthTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAuthTokenStmt: %w", cerr)
		}
	}
	if q.deleteAuthTokenByJWTStmt != nil {
		if cerr := q.deleteAuthTokenByJWTStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAuthTokenByJWTStmt: %w", cerr)
		}
	}
	if q.deleteExpiredAuthStatesStmt != nil {
		if cerr := q.deleteExpiredAuthStatesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteExpiredAuthStatesStmt: %w", cerr)
		}
	}
	if q.deleteExpiredAuthTokensStmt != nil {
		if cerr := q.deleteExpiredAuthTokensStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteExpiredAuthTokensStmt: %w", cerr)
		}
	}
	if q.getAuthStateStmt != nil {
		if cerr := q.getAuthStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAuthStateStmt: %w", cerr)
		}
	}
	if q.getAuthTokenByJWTStmt != nil {
		if cerr := q.getAuthTokenByJWTStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAuthTokenByJWTStmt: %w", cerr)
		}
	}
	if q.getAuthTokensByUserIDStmt != nil {
		if cerr := q.getAuthTokensByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAuthTokensByUserIDStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.updateAuthStateStmt != nil {
		if cerr := q.updateAuthStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAuthStateStmt: %w", cerr)
		}
	}
	if q.updateAuthTokenRefreshTokenStmt != nil {
		if cerr := q.updateAuthTokenRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAuthTokenRefreshTokenStmt: %w", cerr)
		}
	}
	if q.updateUserStmt != nil {
		if cerr := q.updateUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserStmt: %w", cerr)
		}
	}
	if q.updateUserByEmailStmt != nil {
		if cerr := q.updateUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserByEmailStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                              DBTX
	tx                              *sql.Tx
	createAuthStateStmt             *sql.Stmt
	createAuthTokenStmt             *sql.Stmt
	createUserStmt                  *sql.Stmt
	deleteAuthStateStmt             *sql.Stmt
	deleteAuthTokenStmt             *sql.Stmt
	deleteAuthTokenByJWTStmt        *sql.Stmt
	deleteExpiredAuthStatesStmt     *sql.Stmt
	deleteExpiredAuthTokensStmt     *sql.Stmt
	getAuthStateStmt                *sql.Stmt
	getAuthTokenByJWTStmt           *sql.Stmt
	getAuthTokensByUserIDStmt       *sql.Stmt
	getUserByEmailStmt              *sql.Stmt
	getUserByIDStmt                 *sql.Stmt
	updateAuthStateStmt             *sql.Stmt
	updateAuthTokenRefreshTokenStmt *sql.Stmt
	updateUserStmt                  *sql.Stmt
	updateUserByEmailStmt           *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                              tx,
		tx:                              tx,
		createAuthStateStmt:             q.createAuthStateStmt,
		createAuthTokenStmt:             q.createAuthTokenStmt,
		createUserStmt:                  q.createUserStmt,
		deleteAuthStateStmt:             q.deleteAuthStateStmt,
		deleteAuthTokenStmt:             q.deleteAuthTokenStmt,
		deleteAuthTokenByJWTStmt:        q.deleteAuthTokenByJWTStmt,
		deleteExpiredAuthStatesStmt:     q.deleteExpiredAuthStatesStmt,
		deleteExpiredAuthTokensStmt:     q.deleteExpiredAuthTokensStmt,
		getAuthStateStmt:                q.getAuthStateStmt,
		getAuthTokenByJWTStmt:           q.getAuthTokenByJWTStmt,
		getAuthTokensByUserIDStmt:       q.getAuthTokensByUserIDStmt,
		getUserByEmailStmt:              q.getUserByEmailStmt,
		getUserByIDStmt:                 q.getUserByIDStmt,
		updateAuthStateStmt:             q.updateAuthStateStmt,
		updateAuthTokenRefreshTokenStmt: q.updateAuthTokenRefreshTokenStmt,
		updateUserStmt:                  q.updateUserStmt,
		updateUserByEmailStmt:           q.updateUserByEmailStmt,
	}
}
