// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AuthState struct {
	State         string         `json:"state"`
	UserID        uuid.NullUUID  `json:"user_id"`
	Authenticated bool           `json:"authenticated"`
	AuthUrl       sql.NullString `json:"auth_url"`
	ExpiresAt     time.Time      `json:"expires_at"`
	CreatedAt     time.Time      `json:"created_at"`
}

type AuthToken struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	JwtToken     string         `json:"jwt_token"`
	RefreshToken sql.NullString `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
}

type User struct {
	ID            uuid.UUID      `json:"id"`
	Email         string         `json:"email"`
	Name          string         `json:"name"`
	ProfilePic    sql.NullString `json:"profile_pic"`
	GdriveAllowed bool           `json:"gdrive_allowed"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}
