// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAuthState(ctx context.Context, arg CreateAuthStateParams) (AuthState, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAuthState(ctx context.Context, state string) error
	DeleteAuthTokenByUserID(ctx context.Context, userID uuid.UUID) error
	DeleteExpiredAuthStates(ctx context.Context) error
	DeleteExpiredAuthTokens(ctx context.Context) error
	GetAuthState(ctx context.Context, state string) (AuthState, error)
	GetAuthTokenByUserID(ctx context.Context, userID uuid.UUID) (GoogleToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	UpdateAuthState(ctx context.Context, arg UpdateAuthStateParams) (AuthState, error)
	UpdateAuthTokenRefreshToken(ctx context.Context, arg UpdateAuthTokenRefreshTokenParams) error
	UpdateGDriveAllowed(ctx context.Context, arg UpdateGDriveAllowedParams) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserByEmail(ctx context.Context, arg UpdateUserByEmailParams) (User, error)
	UpsertAuthToken(ctx context.Context, arg UpsertAuthTokenParams) (GoogleToken, error)
}

var _ Querier = (*Queries)(nil)
