// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package postgres

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    name,
    profile_pic
) VALUES (
    $1, $2, $3
) RETURNING id, email, name, profile_pic, created_at, updated_at
`

type CreateUserParams struct {
	Email      string         `json:"email"`
	Name       string         `json:"name"`
	ProfilePic sql.NullString `json:"profile_pic"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, arg.Email, arg.Name, arg.ProfilePic)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.ProfilePic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, profile_pic, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.ProfilePic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, profile_pic, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.ProfilePic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    name = COALESCE($1, name),
    profile_pic = COALESCE($2, profile_pic),
    updated_at = NOW()
WHERE id = $3
RETURNING id, email, name, profile_pic, created_at, updated_at
`

type UpdateUserParams struct {
	Name       sql.NullString `json:"name"`
	ProfilePic sql.NullString `json:"profile_pic"`
	ID         uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.queryRow(ctx, q.updateUserStmt, updateUser, arg.Name, arg.ProfilePic, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.ProfilePic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserByEmail = `-- name: UpdateUserByEmail :one
UPDATE users
SET
    name = COALESCE($1, name),
    profile_pic = COALESCE($2, profile_pic),
    updated_at = NOW()
WHERE email = $3
RETURNING id, email, name, profile_pic, created_at, updated_at
`

type UpdateUserByEmailParams struct {
	Name       sql.NullString `json:"name"`
	ProfilePic sql.NullString `json:"profile_pic"`
	Email      string         `json:"email"`
}

func (q *Queries) UpdateUserByEmail(ctx context.Context, arg UpdateUserByEmailParams) (User, error) {
	row := q.queryRow(ctx, q.updateUserByEmailStmt, updateUserByEmail, arg.Name, arg.ProfilePic, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.ProfilePic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
